server:
  port: 8081
  servlet:
    context-path: /openapi/v1

spring:
  application:
    name: OpenApiService
  profiles:
    active:
  #     - with-flyway-migration
  datasource:
    url: jdbc:mysql://localhost:3306/birzha?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 10000
      idle-timeout: 180000
      max-lifetime: 600000
      connection-init-sql: SELECT 1;
      connection-test-query: SELECT 2;
      minimum-idle: 5
      maximum-pool-size: 200
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: none

redis:
  server:
    port: 6379
    host: localhost

referral:
  url: localhost:8080/register?ref=